[tool.poetry]
package-mode = false
authors = ["Jonathan Chang <me@jonathanchang.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34.89"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
