#!/bin/bash

npx wrangler d1 execute d1-example --remote --file schemas/schema.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-1.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-2.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-3.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-4.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-5.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-6.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-7.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-8.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-9.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-a.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-b.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-c.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-d.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-e.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-f.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-g.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-h.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-i.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-j.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-k.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-l.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-m.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-n.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-o.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-p.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-q.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-r.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-s.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-t.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-u.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-v.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-w.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-x.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-y.sql
npx wrangler d1 execute d1-example --remote --file schemas/inserts-z.sql
