#:schema node_modules/wrangler/config-schema.json
name = "scale-score"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "d1-example"
database_id = "66f9c6d2-8fd6-4d57-b610-0e18417422d6"
